name: Reuse our other worklflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml #tp reference another repo it's like [owner]/[repo]/[path]/[workflow.yml]@[branch]
    with:
      who-to-greet: '@esamonte'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo 'Time was ${{ needs.call-workflow.outputs.current-time }}'
      
      
